services:
  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.whoami.rule=Host(`test.ferg.ferguson.pw`)"
#      - "traefik.http.routers.whoami.rule=Host(`lab.ferguson.pw`) && Path(`/overseerr`)"
      - "traefik.http.routers.whoami.rule=Host(`test.ferg.ferguson.pw`) || Host(`lab.ferguson.pw`) && Path(`/overseerr`)"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt-http"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
#      - "traefik.http.routers.whoami.middlewares=ferg-ipwhitelist@docker"
    networks:
      - traefik

networks:
  traefik:
    external: true

