---
version: "2.2"
services:
  # https://github.com/haugene/docker-transmission-openvpn
  '''
  transmission:
    # NOTE: change tag to dev-arm64 instead of dev when using Raspberry Pi
    image: haugene/transmission-openvpn:dev
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
    environment:
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=<FILL>
      - OPENVPN_CONFIG=<FILL>
      - OPENVPN_USERNAME=<FILL>
      - OPENVPN_PASSWORD=<FILL>
      - WEBPROXY_ENABLED=false
    volumes:
      - /media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
'''
  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:3.2.2.5080-ls128
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/radarr:/config
      - /media/movies:/movies
      - /media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.6.1342-ls132
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/sonarr:/config
      - /media/tv:/tv
      - /media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-jackett
  jackett:
    image: linuxserver/jackett:v0.20.422-ls55
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/jackett:/config
      - /media/downloads/watch:/downloads  # transmission watch directory
