version: "2.2"
services:
  # https://github.com/linuxserver/docker-overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      -  ./data/overseerr:/config
#    ports:
#      - 5055:5055
    restart: unless-stopped
    networks:
      - overseerr
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.ferg.ferguson.pw`)"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.routers.overseerr.entryPoints=https"
      - "traefik.http.services.overseerr.loadbalancer.server.scheme=http"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.http.routers.overseerr.middlewares=ferg-ipwhitelist@docker"
      - "com.centurylinklabs.watchtower.enable=true"


  # https://github.com/haugene/docker-transmission-openvpn
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
#    ports:
#      - "9091:9091"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=ca_vancouver,japan,ca_toronto,ca_ontario,mexico
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - WEBPROXY_ENABLED=false
      - TRANSMISSION_HOME=/var/transmission-home/
      - TRANSMISSION_WEB_UI=combustion
      - LOCAL_NETWORK=10.0.0.0/8
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - overseerr
      - default
    volumes:
      - ./config/transmission/openvpn-credentials.txt:/config/openvpn-credentials.txt
      - ./config/transmission/scripts/:/scripts/
      - ./data/transmission:/var/transmission-home
      - /mnt/media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.ferg.ferguson.pw`)"
      - "traefik.http.routers.transmission.tls=true"
      - "traefik.http.routers.transmission.entryPoints=https"
      - "traefik.http.services.transmission.loadbalancer.server.scheme=http"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.http.routers.transmission.middlewares=ferg-ipwhitelist@docker"
      - "com.centurylinklabs.watchtower.enable=true"
  
  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
 #   ports:
 #     - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./data/radarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/downloads/completed:/downloads
    networks:
      - overseerr
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.ferg.ferguson.pw`)"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.entryPoints=https"
      - "traefik.http.services.radarr.loadbalancer.server.scheme=http"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.http.routers.radarr.middlewares=ferg-ipwhitelist@docker"
      - "com.centurylinklabs.watchtower.enable=true"

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
#    ports:
#      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./data/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads/completed:/downloads
    networks:
      - overseerr
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.ferg.ferguson.pw`)"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.entryPoints=https"
      - "traefik.http.services.sonarr.loadbalancer.server.scheme=http"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.http.routers.sonarr.middlewares=ferg-ipwhitelist@docker"
      - "com.centurylinklabs.watchtower.enable=true"

  # https://github.com/linuxserver/docker-jackett
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: always
#    ports:
#      - "9117:9117"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./data/jackett:/config
      - /mnt/media/downloads/watch:/downloads  # transmission watch directory
    networks:
      - overseerr
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.ferg.ferguson.pw`)"
      - "traefik.http.routers.jackett.tls=true"
      - "traefik.http.routers.jackett.entryPoints=https"
      - "traefik.http.services.jackett.loadbalancer.server.scheme=http"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"
      - "traefik.http.routers.jackett.middlewares=ferg-ipwhitelist@docker"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: traefik
  overseerr:
    external: false
