version: "2.2"
services:
  # https://github.com/linuxserver/docker-overseerr
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      -  ./data/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  # https://github.com/haugene/docker-transmission-openvpn
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "9091:9091"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=us_seattle,us_west,ca_vancouver
      - OPENVPN_USERNAME=**None**
      - OPENVPN_PASSWORD=**None**
      - WEBPROXY_ENABLED=false
      - TRANSMISSION_HOME=/var/transmission-home/
      - LOCAL_NETWORK=10.0.0.0/8
    volumes:
      - ./config/transmission/openvpn-credentials.txt:/config/openvpn-credentials.txt
      - ./data/transmission:/var/transmission-home
      - /mnt/media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
  
  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:3.2.2.5080-ls128
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./data/radarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:3.0.6.1342-ls132
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./data/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-jackett
  jackett:
    image: linuxserver/jackett:v0.20.422-ls55
    container_name: jackett
    restart: always
    ports:
      - "9117:9117"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ./data/jackett:/config
      - /mnt/media/downloads/watch:/downloads  # transmission watch directory
