version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:2.6.3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: